
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sexiqdvaqbryhzlkhttm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNleGlxZHZhcWJyeWh6bGtodHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTQ1OTEsImV4cCI6MjA1NzczMDU5MX0.oAMNqBIfnuV5SyYXPRoYh4KicmV9l4TD8r5pB7Mz9Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
